" General
set autoread
set clipboard=unnamed,unnamedplus
set hidden
set nobackup
set noswapfile
set packpath+=~/.config/vim
set title
set ttimeoutlen=10
set updatetime=500
filetype plugin indent on
syntax on

" Color scheme
packadd! onedark
colorscheme onedark

" Appearance
set cursorline
set list
set listchars=tab:>-,trail:-,extends:>,precedes:<,nbsp:%
set noshowmode
set number
set scrolloff=8
set showcmd
set showmatch
set termguicolors
if has('vim_starting')
    let &t_SI = "\e[6 q"
    let &t_EI = "\e[2 q"
    let &t_SR = "\e[4 q"
    autocmd VimLeave * silent !echo -ne "\e[1 q"
endif

" Editor
let mapleader = ' '
let maplocalleader = '\'
set backspace=indent,eol,start
set mouse=a
set smartindent
set virtualedit=onemore
set whichwrap=b,s,h,l,<,>,[,]
set wildmode=list:longest
noremap <Down> }
noremap <Up> {
noremap <Left> ^
noremap <Right> $
inoremap <C-@> <Esc>
nnoremap <C-@> <Esc>
vnoremap <C-@> <Esc>
cnoremap <C-@> <Esc>
nnoremap c "_c
nnoremap x "_x
nnoremap <Leader>l <cmd>nohlsearch<CR>
nnoremap <Leader>o o<Esc>
nnoremap <Leader>O O<Esc>
nnoremap <Leader>w <cmd>w<CR>
nnoremap <Leader>x <cmd>x<CR>
vnoremap < <gv
vnoremap > >gv

" Tab
set expandtab
set shiftwidth=4
set smarttab
set softtabstop=4
set tabstop=4
autocmd FileType markdown setlocal shiftwidth=2 softtabstop=2 tabstop=2

" Search
set hlsearch
set ignorecase
set incsearch
set smartcase
set wrapscan
nnoremap * :let @/ = '\<' . expand('<cword>') . '\>'<CR>:set hlsearch<CR>
nnoremap <Esc><Esc> :nohlsearch<CR>

" Status line
set laststatus=2
let g:lightline = {'colorscheme': 'onedark'}
